name: build_documentation

on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [ master, dev ]
    types:
      - completed

jobs:
  build-documentation:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate documentation
        if: ${{github.event_name == 'push'}}
        run: ./gradlew dokkaHtml

      - name: Deploy API documentation to Github Pages
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: doc
          FOLDER: app/documentation/html